branch-defaults:
  default:
    environment: CHECKOUT-dev
    group_suffix: null
global:
  application_name: CHECKOUT
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
